name: Deploy and Backfill Data

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backfill-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Wait for Railway deployment
        run: |
          echo "Waiting 60 seconds for Railway to deploy the latest changes..."
          sleep 60

      - name: Run backfill script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          cd backend
          python scripts/backfill_metrics.py --years 2 --batch-size 100
